spring:
  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  profiles:
    active: db, security

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug